#include "hermesdb/compaction.hpp"
#include "hermesdb/db.hpp"

#include <charconv>
#include <cctype>
#include <filesystem>
#include <iostream>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

namespace {

struct Options {
  std::filesystem::path path{"lsm.db"};
  std::string compaction{"leveled"};
  bool enable_wal{false};
  bool serializable{false};
};

[[noreturn]] void usage(const char* program, std::string_view error = {}) {
  if (!error.empty()) {
    std::cerr << "error: " << error << "\n\n";
  }
  std::cerr
      << "Usage: " << program << " [options]\n"
      << "  --path PATH                         Database directory (default: lsm.db)\n"
      << "  --compaction simple|leveled|tiered|none\n"
      << "  --enable-wal                        Enable write-ahead logging\n"
      << "  --serializable                      Enable serializable validation\n"
      << "  --help                              Show this help\n";
  std::exit(error.empty() ? 0 : 2);
}

Options parse_args(int argc, char** argv) {
  Options options;
  for (int i = 1; i < argc; ++i) {
    const std::string_view arg(argv[i]);
    if (arg == "--help" || arg == "-h") {
      usage(argv[0]);
    } else if (arg == "--enable-wal") {
      options.enable_wal = true;
    } else if (arg == "--serializable") {
      options.serializable = true;
    } else if (arg == "--path" || arg == "--compaction") {
      if (++i >= argc) {
        usage(argv[0], std::string(arg) + " requires a value");
      }
      if (arg == "--path") {
        options.path = argv[i];
      } else {
        options.compaction = argv[i];
      }
    } else {
      usage(argv[0], std::string("unknown option: ") + std::string(arg));
    }
  }
  if (options.compaction != "simple" && options.compaction != "leveled" &&
      options.compaction != "tiered" && options.compaction != "none") {
    usage(argv[0], "--compaction must be simple, leveled, tiered, or none");
  }
  return options;
}

hermesdb::CompactionOptions compaction_options(std::string_view policy) {
  if (policy == "simple") {
    return hermesdb::SimpleLeveledCompactionOptions{
        .size_ratio_percent = 200,
        .level0_file_num_compaction_trigger = 2,
        .max_levels = 4};
  }
  if (policy == "tiered") {
    return hermesdb::TieredCompactionOptions{
        .num_tiers = 3,
        .max_size_amplification_percent = 200,
        .size_ratio = 1,
        .min_merge_width = 2,
        .max_merge_width = std::nullopt};
  }
  if (policy == "leveled") {
    return hermesdb::LeveledCompactionOptions{
        .level_size_multiplier = 2,
        .level0_file_num_compaction_trigger = 2,
        .max_levels = 4,
        .base_level_size_mb = 128};
  }
  return hermesdb::NoCompactionOptions{};
}

std::uint64_t parse_u64(std::string_view text, std::string_view name) {
  std::uint64_t value{};
  const auto result = std::from_chars(text.data(), text.data() + text.size(), value);
  if (result.ec != std::errc{} || result.ptr != text.data() + text.size()) {
    throw std::runtime_error(std::string(name) + " must be an unsigned integer");
  }
  return value;
}

std::string printable(hermesdb::ByteView bytes) {
  std::string output;
  for (const auto byte : bytes) {
    const auto character = static_cast<unsigned char>(byte);
    if (std::isprint(character) != 0 && character != '\\') {
      output.push_back(static_cast<char>(character));
    } else {
      constexpr char digits[] = "0123456789abcdef";
      output += "\\x";
      output.push_back(digits[character >> 4U]);
      output.push_back(digits[character & 0x0fU]);
    }
  }
  return output;
}

void print_help() {
  std::cout
      << "Commands:\n"
      << "  fill BEGIN END       Put decimal keys in the inclusive range\n"
      << "  del KEY              Delete a key\n"
      << "  get KEY              Read a key\n"
      << "  scan [BEGIN END]     Scan all keys, or an inclusive range\n"
      << "  dump                 Print the LSM structure\n"
      << "  flush                Flush the active memtable\n"
      << "  full_compaction      Compact L0 and L1\n"
      << "  quit | close         Close the database and exit\n"
      << "Values generated by fill have the form value<key>@<epoch>.\n";
}

bool execute(const std::vector<std::string>& words,
             const std::shared_ptr<hermesdb::DB>& db,
             std::uint64_t& epoch) {
  if (words.empty()) {
    return true;
  }
  const auto& command = words[0];
  if (command == "fill") {
    if (words.size() != 3) {
      throw std::runtime_error("usage: fill BEGIN END");
    }
    const auto begin = parse_u64(words[1], "BEGIN");
    const auto end = parse_u64(words[2], "END");
    if (begin > end) {
      throw std::runtime_error("BEGIN must not exceed END");
    }
    for (auto key = begin;; ++key) {
      const auto text = std::to_string(key);
      db->Put(text, "value" + text + "@" + std::to_string(epoch));
      if (key == end) {
        break;
      }
    }
    std::cout << (end - begin + 1) << " values filled with epoch " << epoch
              << '\n';
  } else if (command == "del") {
    if (words.size() != 2) {
      throw std::runtime_error("usage: del KEY");
    }
    db->Delete(words[1]);
    std::cout << words[1] << " deleted\n";
  } else if (command == "get") {
    if (words.size() != 2) {
      throw std::runtime_error("usage: get KEY");
    }
    const auto value = db->Get(words[1]);
    if (value) {
      std::cout << words[1] << '=' << printable(*value) << '\n';
    } else {
      std::cout << words[1] << " not found\n";
    }
  } else if (command == "scan") {
    if (words.size() != 1 && words.size() != 3) {
      throw std::runtime_error("usage: scan [BEGIN END]");
    }
    auto iterator =
        words.size() == 1
            ? db->Scan()
            : db->Scan(hermesdb::KeyBound::Included(words[1]),
                       hermesdb::KeyBound::Included(words[2]));
    std::size_t count{};
    while (iterator.valid()) {
      std::cout << printable(iterator.key()) << '=' << printable(iterator.value())
                << '\n';
      iterator.next();
      ++count;
    }
    std::cout << count << " keys scanned\n";
  } else if (command == "dump") {
    if (words.size() != 1) {
      throw std::runtime_error("usage: dump");
    }
    const auto structure = db->DumpStructure();
    std::cout << structure;
    if (structure.empty() || structure.back() != '\n') {
      std::cout << '\n';
    }
  } else if (command == "flush") {
    if (words.size() != 1) {
      throw std::runtime_error("usage: flush");
    }
    db->ForceFlush();
    std::cout << "flush complete\n";
  } else if (command == "full_compaction") {
    if (words.size() != 1) {
      throw std::runtime_error("usage: full_compaction");
    }
    db->ForceFullCompaction();
    std::cout << "full compaction complete\n";
  } else if (command == "quit" || command == "close") {
    if (words.size() != 1) {
      throw std::runtime_error("usage: " + command);
    }
    db->Close();
    return false;
  } else if (command == "help") {
    print_help();
  } else {
    throw std::runtime_error("unknown command; enter help for a command list");
  }
  ++epoch;
  return true;
}

}  // namespace

int main(int argc, char** argv) {
  std::shared_ptr<hermesdb::DB> db;
  try {
    const auto arguments = parse_args(argc, argv);
    hermesdb::Options options;
    options.block_size = 4096;
    options.target_sst_size = 2U << 20U;
    options.num_memtable_limit = 3;
    options.compaction_options = compaction_options(arguments.compaction);
    options.enable_wal = arguments.enable_wal;
    options.serializable = arguments.serializable;
    db = hermesdb::DB::Open(arguments.path, std::move(options));

    std::cout << "hermesdb CLI (" << arguments.path.string() << ")\n";
    print_help();
    std::uint64_t epoch{};
    std::string line;
    while (std::cout << "hermesdb> " && std::getline(std::cin, line)) {
      std::istringstream input(line);
      std::vector<std::string> words;
      for (std::string word; input >> word;) {
        words.push_back(std::move(word));
      }
      try {
        if (!execute(words, db, epoch)) {
          return 0;
        }
      } catch (const std::exception& error) {
        std::cerr << "error: " << error.what() << '\n';
      }
    }
    db->Close();
    return 0;
  } catch (const std::exception& error) {
    std::cerr << "fatal: " << error.what() << '\n';
    if (db) {
      try {
        db->Close();
      } catch (...) {
      }
    }
    return 1;
  }
}
